# This is a basic workflow to help you get started with Actions

name: Build, Test & Lint

# Controls when the workflow will run
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: github.actor != 'dependabot-bot' && (success() || failure())    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results

      - run: npm run lint
        if: success() || failure()    # run this step even if previous step failed

      - run: npm run format:check
        if: success() || failure()    # run this step even if previous step failed

      - name: Upload
        uses: codecov/codecov-action@v2.1.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - run: npm run build





